### ISSUE TITLE
直接无法运行。cocoa pods是不是不安装不能运行？

### ISSUE THREAD

**Issue by ws270052758** [hadesh/MyRoute#4]

**Comment by hadesh** [comment]
是。。。

**Comment by ws270052758** [comment]
可我安装sudo gem install cocoa pods 报错 ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/pod 这是个什么情况 ，镜像也换成ruby.taobao.com地址了啊

**Comment by hadesh** [comment]
这个。。。就是安装pod的问题了吧。。。。淘宝的源得改成https。其他的我就不知道了。。

**Comment by ws270052758** [comment]
网上搜了下，是mac系统升级到10.11以后安装cocoapods各种花式报错
