### ISSUE TITLE
执行pod intall 之后的编译错误

### ISSUE THREAD

**Issue by taojigu** [hadesh/MyRoute#5]
我执行pod intall 之后

编译

在这两条语句上
MAMapServices.sharedServices().apiKey = APIKey
 AMapSearchServices.sharedServices().apiKey = APIKey
   出现 unresolved 问题，似乎无法识别MAMapServices和这两个类     

/Users/gus/Documents/OpenSource/iOS/MyRoute/MyRoute/AppDelegate.swift:23:9: Use of unresolved identifier 'MAMapServices'
/Users/gus/Documents/OpenSource/iOS/MyRoute/MyRoute/AppDelegate.swift:24:9: Use of unresolved identifier 'AMapSearchServices'

**Comment by taojigu** [comment]
其他类正常使用

**Comment by hadesh** [comment]
你pod install应该是更新到了最新的地图和搜索SDK，4.0.0以上版本key设置方式变了，只需要设置Foundation中的AMapServices就可以了。
