### ISSUE TITLE
关于后台运行

### ISSUE THREAD

**Issue by liupeng826** [hadesh/MyRoute#6]
请问这个并没有使用高德地图的定位sdk，是如何实现连续记录位置的呢？
最近要做一款班车定位软件，后台上传数据到数据库，高德SDK，锁屏之后还会活动吗？后台可以上传吗？

**Comment by hadesh** [comment]
地图SDK本身也是可以定位的。可以实现后台定位，方式和定位SDK是一样的。具体可以参考高德官网的开发指南。http://lbs.amap.com/api/ios-location-sdk/guide/get-location/backgroundlocation/

**Comment by liupeng826** [comment]
请问iOS 定位SDK 和 地图SDK有什么区别呢？ 难道只是一个显示地图一个没有地图也可以定位？ 如果是这样的话，大部分显示地图的app只用地图SDK就可以了？

**Comment by hadesh** [comment]
但是有很多用户想要不显示地图就定位的功能。看具体需求了。如果只是在地图界面才定位，那是使用地图SDK就OK的。定位SDK还有地理围栏、单次逆地理定位等其他功能。

**Comment by liupeng826** [comment]
必须要打开地图才能定位吗？不打开地图要定位，只能用定位SDK？我的需求是用户打开app就要定位，不一定要打开地图，但是用户也可以查看地图标点，是不是就需要同时用这两个SDK？

**Comment by hadesh** [comment]
也可以只用地图SDK，只不过创建出地图不addSubView。
