### ISSUE TITLE
高德SDK能配合Storyboard用吗？

### ISSUE THREAD

**Issue by levi0214** [hadesh/MyRoute#8]
请教一下，高德SDK能配合Storyboard用吗？我试了一下好像不行，如果可以的话，请指教一下。

**Comment by hadesh** [comment]
用的2d还是3d？可以的吧，我们测试xib是可以的。

**Comment by levi0214** [comment]
我的做法是拖了一个MapView进Storyboard，然后企图在下图class中选择到MAMapView，但是没有。不知道是不是我的方法不对？
![storyboard](https://cloud.githubusercontent.com/assets/5380149/19922947/e90d7126-a11f-11e6-8c8d-b9cf96648351.png)

**Comment by hadesh** [comment]
你这个是MK的啊，和我们的mapview没关系。
你试试添加一个普通的view，然后修改class

**Comment by levi0214** [comment]
对哦，我傻了…
刚试了一下可以。谢谢！
